apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephox-hyperlinking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephox-hyperlinking
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ephox-hyperlinking
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ephox-hyperlinking
        image: EXAMPLE-Container-Login-Name.azurecr.io/ephox-hyperlinking:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "ephox-hyperlinking"
      imagePullSecrets:
      - name: kubernetes-SECRET-NAME-HERE
---
apiVersion: v1
kind: Service
metadata:
  name: ephox-hyperlinking
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ephox-hyperlinking
  externalTrafficPolicy: Local
       
    